suorganizer/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from organizer.models import Startup, Tag

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=63)
    slug = models.SlugField(max_length=63, help_text='A label for URL config', unique_for_month='pub_date')
    text = models.TextField()
    pub_date = models.DateField('date published', auto_now_add=True)
    tags = models.ManyToManyField(Tag, related_name='blog_posts')
    startups = models.ManyToManyField(Startup, related_name='blog_posts')

organizer/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=31, unique=True)
    slug = models.SlugField(max_length=31, unique=True, help_text='A label for URL config.')
    
    class Meta:
        ordering = ['name']
        get_latest_by = 'founded_date'

class Startup(models.Model):
    namem = models.CharField(max_length=31, db_index=True)
    slug=models.SlugField(max_length=31, unique=True, help_text='A label for URL config.')
    description = models.TextField()
    founded_date = models.DateField('date founded')
    contact = models.EmailField()
    website = models.URLField(max_length=255)
    tags = models.ManyToManyField(Tag)

class NewsLink(models.Model):
    title = models.CharField(max_length=63)
    pub_date = models.DateField('date published')
    link = models.URLField(max_length=255)
    startup = models.ForeignKey(Startup)

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

organizer/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

organizer/templates/organizer/startup_detail.html
<article>
	<h2>{{ startup.name }}</h2>
	<dl>
		<dt>Date Founded</dt>
		<dd>{{ startup.founded_date</dd>
		<dt>Website</dt>
		<dd>{{ startup.website }}</dd>
		<dt>Contact</dt>
		<dd>{{ startup.contact }}</dd>

		<dt>Tag{{ startup.tags.count | pluralize }}</dt>
		{% for tag in startup.tags.all %}
		<dd><a href="">{{ tag.name | title }}</a></dd>
		{% endfor %}
	</dl>

	<p>{{ startup.description }}</p>

	{% if startup.newslink_set.all %}
	<section>
		<h3>Recent News</h3>
		<ul>
			{% for newslink in startup.newslink_set.all %{
			<li>
				<a href="{{ newslink.link }}">
					{{ newslink.title | title }}
				</a>
			</li>
			{% endfor %}
		</ul>
	</section>
	{% endif %}

	{% if startup.blog_posts.all %}
	<section>
		<h3>Blog Post{{ startup.blog_posts.all | pluralize }}</h3>
		<ul>
			{% for post in startup.blog_posts.all %}
			<li>
				<a href="">
					{{ post.title | title}
				</a>
			</li>
			{% endfor %}
		</ul>
	</section>
	{% endif %}
</article>

organizer/templates/organizer/tag_detail.html
<h2>{{ tag.name | title }} </h2>
{% if tag.startup_set.all %}
	<section>
		<h3>Startup{{tag.startup_set.count | pluralize}}</h3>
		<p>Tag is associated with 
		{{ tag.startup_set.count }}
		startup{{ tag.startup_set.count|pluralize }}.</p>
		<ul>
			{% for startup in tag.startup_set.all %}
				<li>
					<a href="">
						{{ startup.name }}
					</a>
				</li>
			{% endfor %}
		</ul>
	</section>
	{% if tag.blog_posts.all %}
		<section>
			<h3>Blog Posts</h3>
			<ul>
				{% for post in tag.blog_posts.all %}
				<li>
					<a href="">
						{{ post.title }}
					</a>
				</li>
				{% endfor %}
			</ul>
		</section>
	{% endif %}
	{% if not tag.startup_set.all and not tag.blog_posts.all %}
		<p>This tag is not related to any content.</p>
	{% endif %}
{% else %}
	<p>This tag is not related to any startups.</p>
{% endif %}

organizer/templates/organizer/tag_list.html
<h2>Tag List</h2>
{% if tag_list %}
	<ul>
		{% for tag in tag_list %}
		<li>
			<a href="">
				{{ tag.name | title }}
			</a>
		</li>
		{% empty %}
		<li><em>There are currently no Tags available.</em></li>
		{% endfor %}
	</ul>
{% else %}
	<p><em>There are currently no Tags available</em></p>
{% endif %}